// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminStats = `-- name: AdminStats :one
SELECT
    (SELECT COUNT(*) FROM users) AS total_users,
    (SELECT COUNT(*) FROM merchants) AS total_merchants,
    (SELECT COALESCE(SUM(distance_miles), 0)::double precision FROM sessions
     WHERE status IN ('completed', 'suspicious', 'void')) AS total_distance_miles,
    (SELECT COUNT(*) FROM users WHERE is_premium = true) AS premium_users
`

type AdminStatsRow struct {
	TotalUsers         int64   `json:"total_users"`
	TotalMerchants     int64   `json:"total_merchants"`
	TotalDistanceMiles float64 `json:"total_distance_miles"`
	PremiumUsers       int64   `json:"premium_users"`
}

func (q *Queries) AdminStats(ctx context.Context) (AdminStatsRow, error) {
	row := q.db.QueryRow(ctx, adminStats)
	var i AdminStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.TotalMerchants,
		&i.TotalDistanceMiles,
		&i.PremiumUsers,
	)
	return i, err
}

const banUser = `-- name: BanUser :exec
UPDATE users SET is_banned = true WHERE id = $1
`

func (q *Queries) BanUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, banUser, id)
	return err
}

const cancelMerchantChallenges = `-- name: CancelMerchantChallenges :exec
UPDATE challenges
SET expires_at = NOW()
WHERE merchant_id = $1
`

func (q *Queries) CancelMerchantChallenges(ctx context.Context, merchantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelMerchantChallenges, merchantID)
	return err
}

const getAffectedUsersByMerchantBan = `-- name: GetAffectedUsersByMerchantBan :many
SELECT DISTINCT u.phone
FROM challenge_registrations cr
JOIN challenges c ON c.id = cr.challenge_id
JOIN users u ON u.id = cr.user_id
WHERE c.merchant_id = $1 AND cr.status IN ('active', 'pending')
`

func (q *Queries) GetAffectedUsersByMerchantBan(ctx context.Context, merchantID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getAffectedUsersByMerchantBan, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var phone string
		if err := rows.Scan(&phone); err != nil {
			return nil, err
		}
		items = append(items, phone)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMerchantsWithAnalytics = `-- name: ListAllMerchantsWithAnalytics :many
SELECT m.id, m.owner_user_id, m.name, m.category, m.address_lat, m.address_lng, m.logo_url, m.description, m.created_at,
  (SELECT COUNT(*) FROM coupon_redemptions cr
   JOIN coupons cpn ON cpn.id = cr.coupon_id
   JOIN challenges c ON c.id = cpn.challenge_id
   WHERE c.merchant_id = m.id) AS total_redemptions,
  (SELECT COUNT(*) FROM coupon_redemptions cr
   JOIN coupons cpn ON cpn.id = cr.coupon_id
   JOIN challenges c ON c.id = cpn.challenge_id
   WHERE c.merchant_id = m.id
     AND cr.redeemed_at >= NOW() - INTERVAL '7 days') AS weekly_redemptions
FROM merchants m
ORDER BY m.created_at DESC
`

type ListAllMerchantsWithAnalyticsRow struct {
	ID                uuid.UUID          `json:"id"`
	OwnerUserID       uuid.UUID          `json:"owner_user_id"`
	Name              string             `json:"name"`
	Category          string             `json:"category"`
	AddressLat        float64            `json:"address_lat"`
	AddressLng        float64            `json:"address_lng"`
	LogoUrl           string             `json:"logo_url"`
	Description       string             `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	TotalRedemptions  int64              `json:"total_redemptions"`
	WeeklyRedemptions int64              `json:"weekly_redemptions"`
}

func (q *Queries) ListAllMerchantsWithAnalytics(ctx context.Context) ([]ListAllMerchantsWithAnalyticsRow, error) {
	rows, err := q.db.Query(ctx, listAllMerchantsWithAnalytics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllMerchantsWithAnalyticsRow
	for rows.Next() {
		var i ListAllMerchantsWithAnalyticsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Category,
			&i.AddressLat,
			&i.AddressLng,
			&i.LogoUrl,
			&i.Description,
			&i.CreatedAt,
			&i.TotalRedemptions,
			&i.WeeklyRedemptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
