// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
)

const adminStats = `-- name: AdminStats :one
SELECT
    (SELECT COUNT(*) FROM users) AS total_users,
    (SELECT COUNT(*) FROM merchants) AS total_merchants,
    (SELECT COALESCE(SUM(distance_miles), 0)::double precision FROM sessions
     WHERE status IN ('completed', 'suspicious', 'void')) AS total_distance_miles
`

type AdminStatsRow struct {
	TotalUsers         int64   `json:"total_users"`
	TotalMerchants     int64   `json:"total_merchants"`
	TotalDistanceMiles float64 `json:"total_distance_miles"`
}

func (q *Queries) AdminStats(ctx context.Context) (AdminStatsRow, error) {
	row := q.db.QueryRow(ctx, adminStats)
	var i AdminStatsRow
	err := row.Scan(&i.TotalUsers, &i.TotalMerchants, &i.TotalDistanceMiles)
	return i, err
}
