// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO otps (id, phone, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, phone, code_hash, expires_at, used_at, created_at
`

type CreateOTPParams struct {
	ID        uuid.UUID          `json:"id"`
	Phone     string             `json:"phone"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (Otp, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.ID,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOTPForVerify = `-- name: GetOTPForVerify :one
SELECT id, phone, code_hash, expires_at, used_at
FROM otps
WHERE id = $1 AND phone = $2
LIMIT 1
`

type GetOTPForVerifyParams struct {
	ID    uuid.UUID `json:"id"`
	Phone string    `json:"phone"`
}

type GetOTPForVerifyRow struct {
	ID        uuid.UUID          `json:"id"`
	Phone     string             `json:"phone"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

func (q *Queries) GetOTPForVerify(ctx context.Context, arg GetOTPForVerifyParams) (GetOTPForVerifyRow, error) {
	row := q.db.QueryRow(ctx, getOTPForVerify, arg.ID, arg.Phone)
	var i GetOTPForVerifyRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE otps
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}
