// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO merchant_categories (name)
VALUES ($1)
RETURNING name, created_at
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (MerchantCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, name)
	var i MerchantCategory
	err := row.Scan(&i.Name, &i.CreatedAt)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :one
DELETE FROM merchant_categories
WHERE name = $1
RETURNING name, created_at
`

func (q *Queries) DeleteCategory(ctx context.Context, name string) (MerchantCategory, error) {
	row := q.db.QueryRow(ctx, deleteCategory, name)
	var i MerchantCategory
	err := row.Scan(&i.Name, &i.CreatedAt)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT name, created_at
FROM merchant_categories
WHERE name = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (MerchantCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, name)
	var i MerchantCategory
	err := row.Scan(&i.Name, &i.CreatedAt)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT name, created_at
FROM merchant_categories
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]MerchantCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MerchantCategory
	for rows.Next() {
		var i MerchantCategory
		if err := rows.Scan(&i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE merchant_categories
SET name = $2
WHERE name = $1
RETURNING name, created_at
`

type UpdateCategoryParams struct {
	Name   string `json:"name"`
	Name_2 string `json:"name_2"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (MerchantCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.Name, arg.Name_2)
	var i MerchantCategory
	err := row.Scan(&i.Name, &i.CreatedAt)
	return i, err
}
