// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenges.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChallenge = `-- name: CreateChallenge :one
INSERT INTO challenges (id, merchant_id, title, description, target_miles, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, merchant_id, title, description, target_miles, expires_at, created_at
`

type CreateChallengeParams struct {
	ID          uuid.UUID          `json:"id"`
	MerchantID  uuid.UUID          `json:"merchant_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	TargetMiles float64            `json:"target_miles"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (Challenge, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.ID,
		arg.MerchantID,
		arg.Title,
		arg.Description,
		arg.TargetMiles,
		arg.ExpiresAt,
	)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Title,
		&i.Description,
		&i.TargetMiles,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getChallengeByID = `-- name: GetChallengeByID :one
SELECT id, merchant_id, title, description, target_miles, expires_at, created_at
FROM challenges
WHERE id = $1
`

func (q *Queries) GetChallengeByID(ctx context.Context, id uuid.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallengeByID, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Title,
		&i.Description,
		&i.TargetMiles,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveChallengeIDsForUser = `-- name: ListActiveChallengeIDsForUser :many
SELECT cr.challenge_id
FROM challenge_registrations cr
JOIN challenges c ON c.id = cr.challenge_id
WHERE cr.user_id = $1
    AND cr.status IN ('active', 'pending')
    AND c.expires_at > $2
`

type ListActiveChallengeIDsForUserParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListActiveChallengeIDsForUser(ctx context.Context, arg ListActiveChallengeIDsForUserParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveChallengeIDsForUser, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var challenge_id uuid.UUID
		if err := rows.Scan(&challenge_id); err != nil {
			return nil, err
		}
		items = append(items, challenge_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveChallenges = `-- name: ListActiveChallenges :many
SELECT id, merchant_id, title, description, target_miles, expires_at, created_at
FROM challenges
WHERE expires_at > $1
ORDER BY created_at DESC
`

func (q *Queries) ListActiveChallenges(ctx context.Context, expiresAt pgtype.Timestamptz) ([]Challenge, error) {
	rows, err := q.db.Query(ctx, listActiveChallenges, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Title,
			&i.Description,
			&i.TargetMiles,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantChallengesWithCounts = `-- name: ListMerchantChallengesWithCounts :many
SELECT c.id, c.merchant_id, c.title, c.description, c.target_miles, c.expires_at, c.created_at,
       COALESCE(r.participants, 0) AS participants
FROM challenges c
LEFT JOIN (
    SELECT challenge_id, COUNT(*) AS participants
    FROM challenge_registrations
    GROUP BY challenge_id
) r ON r.challenge_id = c.id
WHERE c.merchant_id = $1
ORDER BY c.created_at DESC
`

type ListMerchantChallengesWithCountsRow struct {
	ID           uuid.UUID          `json:"id"`
	MerchantID   uuid.UUID          `json:"merchant_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	TargetMiles  float64            `json:"target_miles"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Participants int64              `json:"participants"`
}

func (q *Queries) ListMerchantChallengesWithCounts(ctx context.Context, merchantID uuid.UUID) ([]ListMerchantChallengesWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listMerchantChallengesWithCounts, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMerchantChallengesWithCountsRow
	for rows.Next() {
		var i ListMerchantChallengesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Title,
			&i.Description,
			&i.TargetMiles,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Participants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChallengeRegistrationCompleted = `-- name: MarkChallengeRegistrationCompleted :exec
UPDATE challenge_registrations
SET status = 'completed'
WHERE user_id = $1 AND challenge_id = $2
`

type MarkChallengeRegistrationCompletedParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ChallengeID uuid.UUID `json:"challenge_id"`
}

func (q *Queries) MarkChallengeRegistrationCompleted(ctx context.Context, arg MarkChallengeRegistrationCompletedParams) error {
	_, err := q.db.Exec(ctx, markChallengeRegistrationCompleted, arg.UserID, arg.ChallengeID)
	return err
}

const registerChallenge = `-- name: RegisterChallenge :one
INSERT INTO challenge_registrations (id, challenge_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (challenge_id, user_id) DO UPDATE SET registered_at = challenge_registrations.registered_at
RETURNING id, challenge_id, user_id, registered_at, status
`

type RegisterChallengeParams struct {
	ID          uuid.UUID `json:"id"`
	ChallengeID uuid.UUID `json:"challenge_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) RegisterChallenge(ctx context.Context, arg RegisterChallengeParams) (ChallengeRegistration, error) {
	row := q.db.QueryRow(ctx, registerChallenge, arg.ID, arg.ChallengeID, arg.UserID)
	var i ChallengeRegistration
	err := row.Scan(
		&i.ID,
		&i.ChallengeID,
		&i.UserID,
		&i.RegisteredAt,
		&i.Status,
	)
	return i, err
}
