// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coupons.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (id, user_id, challenge_id, session_id, code, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, challenge_id, session_id, code, status, issued_at, redeemed_at, redeemed_by_employee_id
`

type CreateCouponParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	ChallengeID uuid.UUID `json:"challenge_id"`
	SessionID   uuid.UUID `json:"session_id"`
	Code        string    `json:"code"`
	Status      string    `json:"status"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.ID,
		arg.UserID,
		arg.ChallengeID,
		arg.SessionID,
		arg.Code,
		arg.Status,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.SessionID,
		&i.Code,
		&i.Status,
		&i.IssuedAt,
		&i.RedeemedAt,
		&i.RedeemedByEmployeeID,
	)
	return i, err
}

const createCouponRedemption = `-- name: CreateCouponRedemption :one
INSERT INTO coupon_redemptions (id, coupon_id, employee_id)
VALUES ($1, $2, $3)
RETURNING id, coupon_id, employee_id, redeemed_at
`

type CreateCouponRedemptionParams struct {
	ID         uuid.UUID `json:"id"`
	CouponID   uuid.UUID `json:"coupon_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
}

func (q *Queries) CreateCouponRedemption(ctx context.Context, arg CreateCouponRedemptionParams) (CouponRedemption, error) {
	row := q.db.QueryRow(ctx, createCouponRedemption, arg.ID, arg.CouponID, arg.EmployeeID)
	var i CouponRedemption
	err := row.Scan(
		&i.ID,
		&i.CouponID,
		&i.EmployeeID,
		&i.RedeemedAt,
	)
	return i, err
}

const getCouponForUpdate = `-- name: GetCouponForUpdate :one
SELECT id, user_id, challenge_id, session_id, code, status, issued_at, redeemed_at, redeemed_by_employee_id
FROM coupons
WHERE code = $1
FOR UPDATE
`

func (q *Queries) GetCouponForUpdate(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponForUpdate, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.SessionID,
		&i.Code,
		&i.Status,
		&i.IssuedAt,
		&i.RedeemedAt,
		&i.RedeemedByEmployeeID,
	)
	return i, err
}

const listCouponsByUser = `-- name: ListCouponsByUser :many
SELECT id, user_id, challenge_id, session_id, code, status, issued_at, redeemed_at, redeemed_by_employee_id
FROM coupons
WHERE user_id = $1
ORDER BY issued_at DESC
`

func (q *Queries) ListCouponsByUser(ctx context.Context, userID uuid.UUID) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listCouponsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChallengeID,
			&i.SessionID,
			&i.Code,
			&i.Status,
			&i.IssuedAt,
			&i.RedeemedAt,
			&i.RedeemedByEmployeeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCouponRedeemed = `-- name: MarkCouponRedeemed :exec
UPDATE coupons
SET status = 'redeemed', redeemed_at = now(), redeemed_by_employee_id = $2
WHERE id = $1
`

type MarkCouponRedeemedParams struct {
	ID                   uuid.UUID   `json:"id"`
	RedeemedByEmployeeID pgtype.UUID `json:"redeemed_by_employee_id"`
}

func (q *Queries) MarkCouponRedeemed(ctx context.Context, arg MarkCouponRedeemedParams) error {
	_, err := q.db.Exec(ctx, markCouponRedeemed, arg.ID, arg.RedeemedByEmployeeID)
	return err
}
