// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (id, merchant_id, user_id, name, phone, code, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, user_id, name, phone, code, status, created_at
`

type CreateEmployeeParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
	UserID     uuid.UUID `json:"user_id"`
	Name       string    `json:"name"`
	Phone      string    `json:"phone"`
	Code       string    `json:"code"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.ID,
		arg.MerchantID,
		arg.UserID,
		arg.Name,
		arg.Phone,
		arg.Code,
		arg.Status,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (id, owner_user_id, name, category, address_lat, address_lng, logo_url, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_user_id, name, category, address_lat, address_lng, logo_url, description, created_at
`

type CreateMerchantParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	AddressLat  float64   `json:"address_lat"`
	AddressLng  float64   `json:"address_lng"`
	LogoUrl     string    `json:"logo_url"`
	Description string    `json:"description"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Category,
		arg.AddressLat,
		arg.AddressLng,
		arg.LogoUrl,
		arg.Description,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Category,
		&i.AddressLat,
		&i.AddressLng,
		&i.LogoUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateEmployee = `-- name: DeactivateEmployee :one
UPDATE employees
SET status = 'inactive'
WHERE id = $1 AND merchant_id = $2
RETURNING id, merchant_id, user_id, name, phone, code, status, created_at
`

type DeactivateEmployeeParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) DeactivateEmployee(ctx context.Context, arg DeactivateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, deactivateEmployee, arg.ID, arg.MerchantID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByCode = `-- name: GetEmployeeByCode :one
SELECT id, merchant_id, user_id, name, phone, code, status, created_at
FROM employees
WHERE merchant_id = $1 AND code = $2
`

type GetEmployeeByCodeParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Code       string    `json:"code"`
}

func (q *Queries) GetEmployeeByCode(ctx context.Context, arg GetEmployeeByCodeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByCode, arg.MerchantID, arg.Code)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByPhone = `-- name: GetEmployeeByPhone :one
SELECT id, merchant_id, user_id, name, phone, code, status, created_at
FROM employees
WHERE phone = $1
`

func (q *Queries) GetEmployeeByPhone(ctx context.Context, phone string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByPhone, phone)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByUserID = `-- name: GetEmployeeByUserID :one
SELECT id, merchant_id, user_id, name, phone, code, status, created_at
FROM employees
WHERE user_id = $1
`

func (q *Queries) GetEmployeeByUserID(ctx context.Context, userID uuid.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUserID, userID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, owner_user_id, name, category, address_lat, address_lng, logo_url, description, created_at FROM merchants
WHERE id = $1
`

func (q *Queries) GetMerchantByID(ctx context.Context, id uuid.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Category,
		&i.AddressLat,
		&i.AddressLng,
		&i.LogoUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantByOwner = `-- name: GetMerchantByOwner :one
SELECT id, owner_user_id, name, category, address_lat, address_lng, logo_url, description, created_at FROM merchants
WHERE owner_user_id = $1
`

func (q *Queries) GetMerchantByOwner(ctx context.Context, ownerUserID uuid.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByOwner, ownerUserID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Category,
		&i.AddressLat,
		&i.AddressLng,
		&i.LogoUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getNearbyMerchants = `-- name: GetNearbyMerchants :many
SELECT id, owner_user_id, name, category, address_lat, address_lng, logo_url, description, created_at,
    (3959 * acos(cos(radians($1::double precision)) * cos(radians(address_lat)) * cos(radians(address_lng) - radians($2::double precision)) + sin(radians($1::double precision)) * sin(radians(address_lat))))::double precision AS distance_miles
FROM merchants
WHERE (3959 * acos(cos(radians($1::double precision)) * cos(radians(address_lat)) * cos(radians(address_lng) - radians($2::double precision)) + sin(radians($1::double precision)) * sin(radians(address_lat)))) <= $3::double precision
ORDER BY distance_miles ASC
`

type GetNearbyMerchantsParams struct {
	Column1 float64 `json:"column_1"`
	Column2 float64 `json:"column_2"`
	Column3 float64 `json:"column_3"`
}

type GetNearbyMerchantsRow struct {
	ID            uuid.UUID          `json:"id"`
	OwnerUserID   uuid.UUID          `json:"owner_user_id"`
	Name          string             `json:"name"`
	Category      string             `json:"category"`
	AddressLat    float64            `json:"address_lat"`
	AddressLng    float64            `json:"address_lng"`
	LogoUrl       string             `json:"logo_url"`
	Description   string             `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DistanceMiles float64            `json:"distance_miles"`
}

func (q *Queries) GetNearbyMerchants(ctx context.Context, arg GetNearbyMerchantsParams) ([]GetNearbyMerchantsRow, error) {
	rows, err := q.db.Query(ctx, getNearbyMerchants, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNearbyMerchantsRow
	for rows.Next() {
		var i GetNearbyMerchantsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Category,
			&i.AddressLat,
			&i.AddressLng,
			&i.LogoUrl,
			&i.Description,
			&i.CreatedAt,
			&i.DistanceMiles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByMerchant = `-- name: ListEmployeesByMerchant :many
SELECT id, merchant_id, user_id, name, phone, code, status, created_at
FROM employees
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEmployeesByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.UserID,
			&i.Name,
			&i.Phone,
			&i.Code,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const merchantDashboardStats = `-- name: MerchantDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM challenges c WHERE c.merchant_id = $1) AS total_challenges,
    (SELECT COUNT(*) FROM coupon_redemptions cr
     JOIN coupons cpn ON cpn.id = cr.coupon_id
     JOIN challenges c ON c.id = cpn.challenge_id
     WHERE c.merchant_id = $1) AS total_redemptions,
    (SELECT COUNT(DISTINCT cr.user_id)
     FROM challenge_registrations cr
     JOIN challenges c ON c.id = cr.challenge_id
     WHERE c.merchant_id = $1) AS active_customers
`

type MerchantDashboardStatsRow struct {
	TotalChallenges  int64 `json:"total_challenges"`
	TotalRedemptions int64 `json:"total_redemptions"`
	ActiveCustomers  int64 `json:"active_customers"`
}

func (q *Queries) MerchantDashboardStats(ctx context.Context, merchantID uuid.UUID) (MerchantDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, merchantDashboardStats, merchantID)
	var i MerchantDashboardStatsRow
	err := row.Scan(&i.TotalChallenges, &i.TotalRedemptions, &i.ActiveCustomers)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET name = COALESCE(NULLIF($3, ''), name),
    status = COALESCE(NULLIF($4, ''), status)
WHERE id = $1 AND merchant_id = $2
RETURNING id, merchant_id, user_id, name, phone, code, status, created_at
`

type UpdateEmployeeParams struct {
	ID         uuid.UUID   `json:"id"`
	MerchantID uuid.UUID   `json:"merchant_id"`
	Column3    interface{} `json:"column_3"`
	Column4    interface{} `json:"column_4"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.MerchantID,
		arg.Column3,
		arg.Column4,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateMerchantProfile = `-- name: UpdateMerchantProfile :one
UPDATE merchants
SET name = $2, category = $3, address_lat = $4, address_lng = $5, logo_url = $6, description = $7
WHERE id = $1
RETURNING id, owner_user_id, name, category, address_lat, address_lng, logo_url, description, created_at
`

type UpdateMerchantProfileParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	AddressLat  float64   `json:"address_lat"`
	AddressLng  float64   `json:"address_lng"`
	LogoUrl     string    `json:"logo_url"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateMerchantProfile(ctx context.Context, arg UpdateMerchantProfileParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantProfile,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.AddressLat,
		arg.AddressLng,
		arg.LogoUrl,
		arg.Description,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Category,
		&i.AddressLat,
		&i.AddressLng,
		&i.LogoUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
