// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (id, merchant_id, name, phone, code, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, merchant_id, name, phone, code, status, created_at
`

type CreateEmployeeParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
	Name       string    `json:"name"`
	Phone      string    `json:"phone"`
	Code       string    `json:"code"`
	Status     string    `json:"status"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.ID,
		arg.MerchantID,
		arg.Name,
		arg.Phone,
		arg.Code,
		arg.Status,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Phone,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (id, owner_user_id, name, category, address_lat, address_lng, logo_url, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_user_id, name, category, address_lat, address_lng, logo_url, description, created_at
`

type CreateMerchantParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	AddressLat  float64   `json:"address_lat"`
	AddressLng  float64   `json:"address_lng"`
	LogoUrl     string    `json:"logo_url"`
	Description string    `json:"description"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Category,
		arg.AddressLat,
		arg.AddressLng,
		arg.LogoUrl,
		arg.Description,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Category,
		&i.AddressLat,
		&i.AddressLng,
		&i.LogoUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByCode = `-- name: GetEmployeeByCode :one
SELECT id, merchant_id, name, phone, code, status, created_at
FROM employees
WHERE merchant_id = $1 AND code = $2
`

type GetEmployeeByCodeParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Code       string    `json:"code"`
}

func (q *Queries) GetEmployeeByCode(ctx context.Context, arg GetEmployeeByCodeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByCode, arg.MerchantID, arg.Code)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Phone,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantByOwner = `-- name: GetMerchantByOwner :one
SELECT id, owner_user_id, name, category, address_lat, address_lng, logo_url, description, created_at FROM merchants
WHERE owner_user_id = $1
`

func (q *Queries) GetMerchantByOwner(ctx context.Context, ownerUserID uuid.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByOwner, ownerUserID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Category,
		&i.AddressLat,
		&i.AddressLng,
		&i.LogoUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listEmployeesByMerchant = `-- name: ListEmployeesByMerchant :many
SELECT id, merchant_id, name, phone, code, status, created_at
FROM employees
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEmployeesByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Phone,
			&i.Code,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const merchantDashboardStats = `-- name: MerchantDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM challenges c WHERE c.merchant_id = $1) AS total_challenges,
    (SELECT COUNT(*) FROM voucher_redemptions vr
     JOIN vouchers v ON v.id = vr.voucher_id
     JOIN challenges c ON c.id = v.challenge_id
     WHERE c.merchant_id = $1) AS total_redemptions,
    (SELECT COUNT(DISTINCT cr.user_id)
     FROM challenge_registrations cr
     JOIN challenges c ON c.id = cr.challenge_id
     WHERE c.merchant_id = $1) AS active_customers
`

type MerchantDashboardStatsRow struct {
	TotalChallenges  int64 `json:"total_challenges"`
	TotalRedemptions int64 `json:"total_redemptions"`
	ActiveCustomers  int64 `json:"active_customers"`
}

func (q *Queries) MerchantDashboardStats(ctx context.Context, merchantID uuid.UUID) (MerchantDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, merchantDashboardStats, merchantID)
	var i MerchantDashboardStatsRow
	err := row.Scan(&i.TotalChallenges, &i.TotalRedemptions, &i.ActiveCustomers)
	return i, err
}
