// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, stripe_payment_intent_id, amount_cents, currency, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, stripe_payment_intent_id, amount_cents, currency, status, created_at
`

type CreatePaymentParams struct {
	UserID                uuid.UUID `json:"user_id"`
	StripePaymentIntentID string    `json:"stripe_payment_intent_id"`
	AmountCents           int32     `json:"amount_cents"`
	Currency              string    `json:"currency"`
	Status                string    `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.StripePaymentIntentID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripePaymentIntentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMRR = `-- name: GetMRR :one
SELECT COALESCE(SUM(amount_cents), 0)::bigint AS mrr_cents
FROM payments
WHERE status = 'succeeded'
  AND created_at >= NOW() - INTERVAL '30 days'
`

func (q *Queries) GetMRR(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getMRR)
	var mrr_cents int64
	err := row.Scan(&mrr_cents)
	return mrr_cents, err
}
