// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, challenge_id, start_time, start_lat, start_lng, steps_start, miles_start, status, hmac_secret)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, challenge_id, start_time, end_time, start_lat, start_lng, end_lat, end_lng,
          steps_start, steps_end, miles_start, miles_end, distance_miles, status, hmac_secret, created_at, updated_at
`

type CreateSessionParams struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	ChallengeID uuid.UUID          `json:"challenge_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	StartLat    float64            `json:"start_lat"`
	StartLng    float64            `json:"start_lng"`
	StepsStart  int32              `json:"steps_start"`
	MilesStart  float64            `json:"miles_start"`
	Status      string             `json:"status"`
	HmacSecret  string             `json:"hmac_secret"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ChallengeID,
		arg.StartTime,
		arg.StartLat,
		arg.StartLng,
		arg.StepsStart,
		arg.MilesStart,
		arg.Status,
		arg.HmacSecret,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.StartTime,
		&i.EndTime,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.StepsStart,
		&i.StepsEnd,
		&i.MilesStart,
		&i.MilesEnd,
		&i.DistanceMiles,
		&i.Status,
		&i.HmacSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, challenge_id, start_time, end_time, start_lat, start_lng, end_lat, end_lng, steps_start, steps_end, miles_start, miles_end, distance_miles, status, hmac_secret, created_at, updated_at FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.StartTime,
		&i.EndTime,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.StepsStart,
		&i.StepsEnd,
		&i.MilesStart,
		&i.MilesEnd,
		&i.DistanceMiles,
		&i.Status,
		&i.HmacSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionForUser = `-- name: GetSessionForUser :one
SELECT id, user_id, challenge_id, start_time, end_time, start_lat, start_lng, end_lat, end_lng, steps_start, steps_end, miles_start, miles_end, distance_miles, status, hmac_secret, created_at, updated_at FROM sessions
WHERE id = $1 AND user_id = $2
`

type GetSessionForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSessionForUser(ctx context.Context, arg GetSessionForUserParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionForUser, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.StartTime,
		&i.EndTime,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.StepsStart,
		&i.StepsEnd,
		&i.MilesStart,
		&i.MilesEnd,
		&i.DistanceMiles,
		&i.Status,
		&i.HmacSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionEnd = `-- name: UpdateSessionEnd :exec
UPDATE sessions
SET end_time = $2, end_lat = $3, end_lng = $4, steps_end = $5, miles_end = $6, updated_at = now()
WHERE id = $1
`

type UpdateSessionEndParams struct {
	ID       uuid.UUID          `json:"id"`
	EndTime  pgtype.Timestamptz `json:"end_time"`
	EndLat   float64            `json:"end_lat"`
	EndLng   float64            `json:"end_lng"`
	StepsEnd int32              `json:"steps_end"`
	MilesEnd float64            `json:"miles_end"`
}

func (q *Queries) UpdateSessionEnd(ctx context.Context, arg UpdateSessionEndParams) error {
	_, err := q.db.Exec(ctx, updateSessionEnd,
		arg.ID,
		arg.EndTime,
		arg.EndLat,
		arg.EndLng,
		arg.StepsEnd,
		arg.MilesEnd,
	)
	return err
}

const updateSessionStatusAndDistance = `-- name: UpdateSessionStatusAndDistance :exec
UPDATE sessions
SET status = $2, distance_miles = $3, updated_at = now()
WHERE id = $1
`

type UpdateSessionStatusAndDistanceParams struct {
	ID            uuid.UUID `json:"id"`
	Status        string    `json:"status"`
	DistanceMiles float64   `json:"distance_miles"`
}

func (q *Queries) UpdateSessionStatusAndDistance(ctx context.Context, arg UpdateSessionStatusAndDistanceParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatusAndDistance, arg.ID, arg.Status, arg.DistanceMiles)
	return err
}
