// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, phone, role)
VALUES ($1, $2, $3)
RETURNING id, phone, name, avatar_url, role, created_at, is_banned, is_premium
`

type CreateUserParams struct {
	ID    uuid.UUID `json:"id"`
	Phone string    `json:"phone"`
	Role  UserRole  `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Phone, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.IsBanned,
		&i.IsPremium,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, name, avatar_url, role, created_at, is_banned, is_premium
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.IsBanned,
		&i.IsPremium,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, name, avatar_url, role, created_at, is_banned, is_premium
FROM users
WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.IsBanned,
		&i.IsPremium,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = $2, avatar_url = $3
WHERE id = $1
RETURNING id, phone, name, avatar_url, role, created_at, is_banned, is_premium
`

type UpdateUserProfileParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	AvatarUrl string    `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.IsBanned,
		&i.IsPremium,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = $2
WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role UserRole  `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const upgradeUserToPremium = `-- name: UpgradeUserToPremium :exec
UPDATE users
SET is_premium = true
WHERE id = $1
`

func (q *Queries) UpgradeUserToPremium(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, upgradeUserToPremium, id)
	return err
}
