// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vouchers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVoucher = `-- name: CreateVoucher :one
INSERT INTO vouchers (id, user_id, challenge_id, session_id, code, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, challenge_id, session_id, code, status, issued_at, redeemed_at, redeemed_by_employee_id
`

type CreateVoucherParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	ChallengeID uuid.UUID `json:"challenge_id"`
	SessionID   uuid.UUID `json:"session_id"`
	Code        string    `json:"code"`
	Status      string    `json:"status"`
}

func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, createVoucher,
		arg.ID,
		arg.UserID,
		arg.ChallengeID,
		arg.SessionID,
		arg.Code,
		arg.Status,
	)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.SessionID,
		&i.Code,
		&i.Status,
		&i.IssuedAt,
		&i.RedeemedAt,
		&i.RedeemedByEmployeeID,
	)
	return i, err
}

const createVoucherRedemption = `-- name: CreateVoucherRedemption :one
INSERT INTO voucher_redemptions (id, voucher_id, employee_id)
VALUES ($1, $2, $3)
RETURNING id, voucher_id, employee_id, redeemed_at
`

type CreateVoucherRedemptionParams struct {
	ID         uuid.UUID `json:"id"`
	VoucherID  uuid.UUID `json:"voucher_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
}

func (q *Queries) CreateVoucherRedemption(ctx context.Context, arg CreateVoucherRedemptionParams) (VoucherRedemption, error) {
	row := q.db.QueryRow(ctx, createVoucherRedemption, arg.ID, arg.VoucherID, arg.EmployeeID)
	var i VoucherRedemption
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.EmployeeID,
		&i.RedeemedAt,
	)
	return i, err
}

const getVoucherForUpdate = `-- name: GetVoucherForUpdate :one
SELECT id, user_id, challenge_id, session_id, code, status, issued_at, redeemed_at, redeemed_by_employee_id
FROM vouchers
WHERE code = $1
FOR UPDATE
`

func (q *Queries) GetVoucherForUpdate(ctx context.Context, code string) (Voucher, error) {
	row := q.db.QueryRow(ctx, getVoucherForUpdate, code)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.SessionID,
		&i.Code,
		&i.Status,
		&i.IssuedAt,
		&i.RedeemedAt,
		&i.RedeemedByEmployeeID,
	)
	return i, err
}

const listVouchersByUser = `-- name: ListVouchersByUser :many
SELECT id, user_id, challenge_id, session_id, code, status, issued_at, redeemed_at, redeemed_by_employee_id
FROM vouchers
WHERE user_id = $1
ORDER BY issued_at DESC
`

func (q *Queries) ListVouchersByUser(ctx context.Context, userID uuid.UUID) ([]Voucher, error) {
	rows, err := q.db.Query(ctx, listVouchersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voucher
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChallengeID,
			&i.SessionID,
			&i.Code,
			&i.Status,
			&i.IssuedAt,
			&i.RedeemedAt,
			&i.RedeemedByEmployeeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVoucherRedeemed = `-- name: MarkVoucherRedeemed :exec
UPDATE vouchers
SET status = 'redeemed', redeemed_at = now(), redeemed_by_employee_id = $2
WHERE id = $1
`

type MarkVoucherRedeemedParams struct {
	ID                   uuid.UUID   `json:"id"`
	RedeemedByEmployeeID pgtype.UUID `json:"redeemed_by_employee_id"`
}

func (q *Queries) MarkVoucherRedeemed(ctx context.Context, arg MarkVoucherRedeemedParams) error {
	_, err := q.db.Exec(ctx, markVoucherRedeemed, arg.ID, arg.RedeemedByEmployeeID)
	return err
}
